title: JunJae Jeong # your name (or website title) here
logo: "/images/JJJ.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  사람과 조직을 살리는 HRDer
  <br><br>
  
  <a href="https://www.linkedin.com/in/hrdertriplej/?skipRedirect=true">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@0.2.0
plugins:
- jekeyll-remote-theme
google_analytics:UA-000000-0
